FROM ubuntu:focal as decker

#set the encoding on UTF-8, so the parser works correctly, german language is also added for umlaute
#source of fix: https://blog.mkowalski.net/2016/05/16/solving-locale-issues-with-docker-containers/
RUN apt-get update && apt-get install --reinstall -y locales && \
    sed -i 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen de_DE.UTF-8
ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE
ENV LC_ALL de_DE.UTF-8
RUN dpkg-reconfigure --frontend noninteractive locales

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y install tzdata

RUN apt-get install -y \
    graphviz \
    gnuplot \
    rsync \
    unzip \
    zip \
    wget

RUN  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg --unpack google-chrome-stable_current_amd64.deb && apt-get install -f -y

RUN ln -s /usr/bin/google-chrome-stable /usr/bin/chrome

COPY decker /usr/bin/decker 

WORKDIR /decker

ENTRYPOINT ["decker"]
