# Default meta data

poll-server: wss://tramberend.bht-berlin.de/quizzer/quiz
# poll-server: ws://localhost:3003/quiz
save-polls: true

# enable some experimental features
experiments:
  # fragment templates are needed for Codapi live-code support
  fragment-templates: true

# highlightjs: "xcode"

palette:
  colors:
    light: # OKSolar (https://meat.io/oksolar)
      - "#F3F2F1"
      - "#E6E5E1"
      - "#8faaab"
      - "#98a8a8"
      - "#657377"
      - "#5b7279"
      - "#212C37"
      - "#171F27"
      - "#dd459d"
      - "#f23749"
      - "#d56500"
      - "#ac8300"
      - "#819500"
      - "#259d94"
      - "#2b90d8"
      - "#7d80d1"
    dark: # OKSolar (https://meat.io/oksolar)
      - "#171F27"
      - "#212C37"
      - "#5b7279"
      - "#657377"
      - "#98a8a8"
      - "#8faaab"
      - "#E6E5E1"
      - "#F3F2F1"
      - "#dd459d"
      - "#f23749"
      - "#d56500"
      - "#ac8300"
      - "#819500"
      - "#259d94"
      - "#2b90d8"
      - "#7d80d1"
  contrast: 0.3

reveal:
  reveal:
  backgroundTransition: "slide"
  center: true
  controls: true
  fragmentInURL: true
  fragments: true
  hash: true
  height: 1080
  help: false
  hideCursorTime: 2000
  hideInactiveCursor: true
  history: false
  keyboard: true
  margin: 0.05
  overview: true
  progress: true
  slideNumber: true
  touch: true
  transition: "slide"
  vertical-slides: true
  viewDistance: 2
  width: 1920

css-variables:
  block-border-radius: 0.2em;
