provisioning: Copy
# Sane defaults for reval.js
backgroundTransition: "none"
center: true
controls: true
fragmentInURL: true
fragments: true
hash: true
help: true
hideCursorTime: 2000
hideInactiveCursor: true
history: false
keyboard: true
menu: true
overview: true
progress: true
touch: true
vertical-slides: true
transition: "none"
title: "|title|"
test123: "test123"
# These are some sane defaults we need
margin: 0.05
margin-columns: 0em
font-size-base: 28px
align-global: left
spacing-vertical-base: 0.5em
border-decoration-width: 20px
border-decoration-padding: 10px
border-decoration-style: solid
# default settings for whiteboard buttons
whiteboard-icon-size: 2vmin
whiteboard-active-color: rgb(42,157,223)
whiteboard-inactive-color: lightgrey
whiteboard-background-color: rgb(250,250,250)
# Language dictionary. Currently for quiz elements
dictionary:
  de: 
    exam:
      solution: Lösung
      solve-button: Lösen
      reset-button: Zurücksetzen
      placeholder: Antwort eingeben
      points: Punkte
      Easy: Leicht
      Medium: Mittelschwer
      Hard: Schwer
    quiz:
      solution: Lösung
      reset-button: Zurücksetzen
      input-placeholder: Eingeben und 'Enter'
      qmi-drag-hint: Objekte per Drag&Drop ziehen...
      qmi-drop-hint: ...und hier in die richtige Kategorie einsortieren.
  en:
    exam:
      solution: Solution
      solve-button: Solve
      reset-button: Reset
      placeholder: Type in answer
      points: Points
      Easy: Easy
      Medium: Medium
      Hard: Hard
    quiz:
      solution: Show Solution
      reset-button: Reset
      input-placeholder: Type and press 'Enter'
      qmi-drag-hint: Drag items from here...
      qmi-drop-hint: ...and put them here into the correct category.

