name: Check and verify that building works on NixOS
on:
  push:
permissions:
  contents: read

jobs:
  nixos_verify:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out project
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v31
    - uses: DeterminateSystems/magic-nix-cache-action@v13
    - name: First check of nix flake
      # catches syntax errors or misconfigurations of the flake on all systems
      run: nix flake check --all-systems
    - name: Try entering devshell
      # causes exit code (=failure) if current system's artifact is unavailable
      run: nix develop
    - name: Install and setup direnv
      run: |
        sudo apt-get update && sudo apt-get install -y direnv
        echo "export USE_NIX=true" > .envrc.private
        direnv allow .
        direnv export gha > "$GITHUB_ENV"
    - name: Build project
      run: |
        make
